# Configuration file for codecov.io
# https://docs.codecov.io/docs/codecovyml-reference

codecov:
  branch: main
  bot: "codecov-io"
  ci:
    - "github.com"
  max_report_age: 24
  disable_default_path_fixes: no  # yamllint disable-line rule:truthy
  require_ci_to_pass: yes  # yamllint disable-line rule:truthy
  notify:
    after_n_builds: 11
    wait_for_ci: yes  # yamllint disable-line rule:truthy

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
